; SACA POR EL PUERTO B EL VALOR 0X55
; SACA POR EL PUERTO C EL VALOR 0XAA
; SACA POR EL PUERTO D EL VALOR 0XCC
    
		PROCESSOR	16F877A
		INCLUDE		<p16f877a.inc>
		__CONFIG	_HS_OSC	& _WDT_OFF & _LVP_OFF
		ORG		0X0000

; PARA CMBIAR DE BANCO SE MODIFICAN LOS BITS
; RP1 Y RP0 DEL REG. STATUS
; 0	0   BANCO 0
; 0	1   BANCO 1		
; 1	0   BANCO 2
; 1	1   BANCO 3		
		MOVLW		0X55		; CARGAMOS LOS VALORES A MOSTRAR
		MOVWF		PORTB
		MOVLW		0XAA
		MOVWF		PORTC
		MOVLW		0XCC
		MOVWF		PORTD
		BSF		STATUS,RP0	; NOS MOVEMOS AL BANCO 1
		CLRF		TRISB		; PUERTO B COMO SALIDA
		CLRF		TRISC		; PUERTO C COMO SALIDA
		CLRF		TRISD		; PUERTO D COMO SALIDA
SINFIN:		GOTO		SINFIN		; PARA DEJAR EN BUCLE EL PIC
		END