;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;    
;		    PWM CON RUTINAS DE TIEMPO
;   PORTD = PWM F = 1KHZ, CADA QUE SE APRIETE A PB.1 CAMBIAR
;   EL PWM DE:
;   A) 0% A 5%
;   B) 5% A 20%
;   C) 20% A 50%
;   D) 50% A 80%
;   E) 80% A 0%
;   MOSTRAR PE.2 = 1 PARA COMPARAR CON EL PWM
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    
;   CONFIGURACION DEL PIC.......................................................
    
		PROCESSOR	16F877A
		INCLUDE		<p16f877a.inc>
		INCLUDE		</home/vill4in/MPLABXProjects/Library.X/RutinasTiempo.asm>
		__CONFIG	0X3F31
		ORG		0X0000
		
;   CONFIGURACION DE LOS PUERTOS................................................
		
		BCF		STATUS,RP0
		BCF		STATUS,RP1
		CLRF		PORTA
		CLRF		PORTB
		CLRF		PORTC
		CLRF		PORTD
		BSF		STATUS,RP0
		CLRF		TRISD
		BCF		TRISE,2
		BCF		STATUS,RP0
		BSF		PORTE,2
		
;   PROGRAMA PRINCIPAL
;   SE REALIZA EL AJUSTE EN LOS TIEMPOS DE TRABAJO E IDLE PARA CONTEMPLAR
;   LOS CICLOS QUE SE USAN DURANTE LAS INSTRUCCIONES INTERMEDIAS EN EL CAMBIO
;   DE  ESTADOS
		
INICIO:		BTFSS		PORTB,1
		GOTO		$-1
		SUBT2V		.32,.111	; DELAY DE 25MS
		NOP
		BTFSC		PORTB,1
		GOTO		$-1
		SUBT2V		.32,.111 
		NOP
		
CINCOPORC:	COMF		PORTD,F
		SUBT1V		.6		; DUTY CICLE DE 0.05MS; 50 CICLOS
		NOP
		NOP
		COMF		PORTD,F		; 49 + 1 CICLOS
		SUBT2V		.14,.9		; DELAY DE 0.95 MS
		NOP
		BTFSS		PORTB,1
		GOTO		CINCOPORC
		SUBT2V		.32,.111	; DELAY DE 25MS
		NOP
		BTFSC		PORTB,1
		GOTO		$-1
		SUBT2V		.32,.111
		NOP
		
VEINTEPORC:	COMF		PORTD,F
		SUBT2V		.6,.4		; DUTY CICLE DE 0.2 MS
		COMF		PORTD,F		; 199 + 1 CICLOS
		SUBT1V		.113		; DELAY DE 0.796 MS
		BTFSS		PORTB,1
		GOTO		VEINTEPORC
		SUBT2V		.32,.111	; DELAY DE 25MS
		NOP
		BTFSC		PORTB,1
		GOTO		$-1
		SUBT2V		.32,.111
		NOP
		
CINCUENTAPORC:	COMF		PORTD,F
		SUBT2V		.4,.17		; DUTY CICLE DE 0.50MS
		COMF		PORTD,F
		SUBT1V		.70		; DELAY DE 0.50MS
		NOP				; 495 + 1 CICLOS
		BTFSS		PORTB,1
		GOTO		CINCUENTAPORC
		SUBT2V		.32,.111	; DELAY DE 25MS
		NOP
		BTFSC		PORTB,1
		GOTO		$-1
		SUBT2V		.32,.111
		NOP
		
OCHENTAPORC:	COMF		PORTD,F
		SUBT2V		.2,.56		; DUTY CICLE DE 0.80MS
		COMF		PORTD,F
		SUBT1V		.27		; DELAY DE 0.20MS
		NOP
		NOP				; 194 + 2 CICLOS
		BTFSS		PORTB,1
		GOTO		OCHENTAPORC
		SUBT2V		.32,.111	; DELAY DE 25MS
		NOP
		BTFSC		PORTB,1
		GOTO		$-1
		SUBT2V		.32,.111
		NOP	
		GOTO		CINCOPORC
		
		END
		
		
    