;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;			ANTIREBOTE Y PARPADEO
;
;	AL PRESIONAR EL BOTON CONECTADO EN PE.0 SE SCARA EL VALOR 
;	0XF0 POR EL PUERTO D DURANTE 200MS Y DESPUES EL VALOR 0X0F
;	POR EL MISMO PUERTO D POR 200 MS
;		
;	SE EMPLEARA UNA RUTINA ANTIREBOTES EN EL PIN DONDE SE
;	ENCUENTRA EL BOTON, LA RUTINA DE PARPADEO COMENZARA HASTA QUE
;	EL BOTON SEA PRESIONADO Y SOLTADO
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;   CONFIGURACION DEL PIC.......................................................
    
		PROCESSOR	16F877A
		INCLUDE		<p16f877a.inc>
		INCLUDE		</home/vill4in/MPLABXProjects/Library.X/RutinasTiempo.asm>
		__CONFIG	0X3F31
		ORG		0X0000
		
;   CONFIGURACION DE LOS PUERTOS................................................

		CLRF		PORTA
		CLRF		PORTB
		CLRF		PORTC
		CLRF		PORTD
		BSF		STATUS,RP0
		CLRF		TRISD
		BCF		STATUS,RP0

;   PROGRAMA PRINCIPAL
		
;		BTFSS		PORTB,1
;		GOTO		$-1
;		SUBT2V		.32,.111	; 25 MS PARA EVITAR EL REBOTE
;		BTFSC		PORTB,1
;		GOTO		$-1
;		SUBT2V		.32,.111	; 25 MS PARA EVITAR EL REBOTE
		
PARPADEO:	MOVLW		0XF0
		MOVWF		PORTD
		SUBT2V		.243,.117	; DELAY DE 200MS
		NOP				; COMPLETA LOS CICLOS FALTANTES
		NOP
		NOP
		NOP
		MOVLW		0X0F
		MOVWF		PORTD
		;SWAPF		PORTD,F
		SUBT2V		.243,.117	; DELAY DE 200MS
		NOP				; COMPLETA LOS CICLOS FALTANTES
		NOP				
		NOP
		NOP
		GOTO		PARPADEO
		END