;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;			EJERCICIO 09
;
;	SE LEE EL VALOR DE LOS PUERTOS B Y C
;	SI PB > PC ENTONCES PD SACA 0X12 Y PA 0XCC
;	SI PB < PC ENTONCES PD SACA 0X69 Y PA 0X7B
;	SI PB == PC ENTONCES PD SACA 0XE1 Y PA 0XDD
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    
;   CONFIGURACION DEL PIC.......................................................
    
		PROCESSOR	16F877A
		INCLUDE		<p16f877a.inc>
		__CONFIG	0X3F31
		ORG		0X0000
		
;   CONFIGURACION DE LOS PUERTOS................................................

		CLRF		PORTA
		CLRF		PORTB
		CLRF		PORTC
		CLRF		PORTD
		BSF		STATUS,RP0
		CLRF		TRISA
		CLRF		TRISD
		BCF		STATUS,RP0
		
;   PROGRAMA PRINCIPAL..........................................................
;   SI EL BIT DE ACARREO SE PONE EN 1: EL RESULTADO ES CERO O POSITIVO
;   SI EL BIT DE ACARREO SE PONE EN 0: EL RESULTADO ES NEGATIVO
;   SI EL ZERO-BIT EN EL REGISTRO STATUS ES 1 LA OPERACION TUVO COMO
;   RESULTADO 0, INDICANDONOS QUE LOS VALORES SON IDENTICOS, DE LO 
;   CONTRARIO, ZERO-BIT SERA 0 INDICANDONOS QUE NO SON IGUALES
		
REPITE:		MOVF		PORTC,W
		SUBWF		PORTB,0	    ; PB - PC
		BTFSS		STATUS,C
		GOTO		PB_MENOR
		GOTO		PB_MAYOR_IG
		GOTO		REPITE
PB_MENOR:	MOVLW		0X69
		MOVWF		PORTD
		MOVLW		0X7B
		MOVF		PORTA
		GOTO		REPITE
PB_MAYOR_IG:	BTFSS		STATUS,Z
		GOTO		PB_MAYOR
		MOVLW		0XE1
		MOVWF		PORTD
		MOVLW		0XDD
		MOVF		PORTA
		GOTO		REPITE
PB_MAYOR:	MOVLW		0X12
		MOVWF		PORTD
		MOVLW		0XCC
		MOVF		PORTA
		GOTO		REPITE
		END

		