;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;		    SUBRUTINAS PARA LCD HD44780U DE HITACHI
;
;	IMPLEMENTACION MEDIANTE SUBRUTINAS DE LAS INSTRUCCIONES DEL 
;       CONTROLADOR DEL LCD EN MODO DE 4-BITS
;	
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;............................INSTRUCCIONES......................................
;...............................................................................
    
#DEFINE		    CLR_DISP:	RETLW	'0B00000001'
#DEFINE		    RETURN_H:	RETLW	'0B00000010'
;   SE REQUIERE MASCARA EN LAS SIGUIENTES INSTRUCCIONES.........................
    
;   BIT-4: ESTABLECE LA LONGITUD DE LA INTERFACE DE DATOS 1-8-BITS; 0-4-BITS
;   EN ESTE CASO SIMPRE SERA DE 4-BITS
;   BIT-3: NUMERO DE LINEAS DEL DISPLAY 1-2 LINEAS; 0-1 LINEA
;   BIT-2: FUENTE DE CARACTERES: 1-5*10; 0-5*8
;   BIT-1,0 NO IMPORTAN
CBLOCK	0X20
    AUX_LINEAS, AUX_FUENTE
ENDC
FUNCION_SET	    MACRO	LCD_PORT, N_LINEAS, FUENTE
		    MOVLW	N_LINEAS
		    MOVWF	AUX_LINEAS 
		    MOVLW	FUENTE
		    MOVWF	AUX_FUENTE
		    RLF		AUX_LINEAS,F
		    RLF		AUX_LINEAS,F
		    RLF		AUX_FUENTE,F
		    RLF		AUX_FUENTE,F
		    RLF		AUX_FUENTE,F
		    RLF		AUX_FUENTE,F
		    MOVLW	'0B00111111'
		    ANDWF	AUX_LINEAS,W
		    ANDWF	AUX_FUENTE,W
		    MOVWF	HIGH	LCD_PORT
		    
    
    
    
    
    
;   BIT-2 SIEMPRE 1, BIT-1: 1-INCREMENTO; 0-DECREMENTO DE LA DIRECCION
;   DDRAM CADA QUE SE LEE O ESCRIBE EN ELLA, BIT-0 DISPLAY SHIFT  
ENTRY_MODE_SET:	    RETLW	'0B00000111' 

;   BIT-3 SIEMPRE 1, BIT-2: DISPLAY 1-ON; 0-OFF, BIT-1: CURSOR 1-ON; O-OFF
;   BIT-0: BLINKING CURSOR 1-ON; O-OFF
DISPLAY_ON_OFF:	    RETLW	'0B00001111'

;   MUEVE EL CURSOR O MUEVE EL DISPLAY SIN ALTERAR LOS CONTENIDOS DE LA RAM
;   BIT-4 SIEMPRE 1, BIT-3: DISPLAY SHIFT 1-DISPLAY-SHIDT; 0-CURSOR MOVE
;   BIT-2: SHIFT TO 1-RIGHT; 0-LEFT, BIT-1,0 NO IMPORTAN
CURSOR_DISPLAY_S:   RETLW	'0B00011111'

;   BIT-4: ESTABLECE LA LONGITUD DE LA INTERFACE DE DATOS 1-8-BITS; 0-4-BITS
;   EN ESTE CASO SIMPRE SERA DE 4-BITS
;   BIT-3: NUMERO DE LINEAS DEL DISPLAY 1-2 LINEAS; 0-1 LINEA
;   BIT-2: FUENTE DE CARACTERES: 1-5*10; 0-5*8
;   BIT-1,0 NO IMPORTAN
FUNCION_SET:	    RETLW	'0B00111111'

; SET_CGRAM_ADD - AUN NO IMPLEMENTADA

;   ESTABLECE LA DIRECCION DE LA DDRAM
;   BIT-7 SIEMPRE 1, BIT6-0 LA DIRECCION EN LA DDRAM A LA QUE SE DESEA
;   ACCEDER
SET_DDRAM_ADD:	    RETLW	'0B11111111'
    
;   READ_BUSY_FLAG - AUN NO IMPLEMENTADA

