;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;		    SUBRUTINAS DE TIEMPO
;
;	MACROS DE SUBRUTINAS DE TIEMPO DE UNA, DOS Y TRES VARIABLES
;	
;	SE EMPLEAN LOS REGISTROS RAM DE 0X60 HASTA 0X68 PARA ALMACENAR
;	LAS VARIABLES
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    
;   MACRO Y SUBRUTINA DE UNA VARIABLE, CICLOS_MAQ_MAX = 1797
;   SE OCUPA LA DIRECCION 0X60 DE LA RAM PARA GUARDAR EL VALOR DE VAR1
    
SUBT1V	    MACRO	VAR1
	    MOVLW	VAR1
	    MOVWF	0X60
ST1V:	    NOP
	    NOP
	    NOP
	    NOP
	    DECFSZ	0X60,F
	    GOTO	ST1V
	    NOP				; PARA SIMULAR LOS CICLOS DE RETURN Y
	    NOP				; LOS DE CALL
	    NOP
	    NOP
	    ENDM
    
;   MACRO Y SUBRUTINA DE DOS VARIABLES, CICLOS_MAQ_MAX = 459,783
;   SE OCUPA LA DIRECCION 0X61,62 DE LA RAM PARA GUARDAR EL VALOR DE VAR1,
;   VAR2
;   TAMBIEN SE OCUPA LA DIRECCION  0X63 COMO REGISTRO AUXILIAR EN EL DECREMENTO
    
SUBT2V	    MACRO	VAR1,VAR2
	    MOVLW	VAR1
	    MOVWF	0X61		; VALOR DE MAYOR PESO EN ANIDACION
	    MOVLW	VAR2
	    MOVWF	0X62
ST2V:	    MOVF	0X62,W
	    MOVWF	0X63
DECRE2V:    NOP
	    NOP
	    NOP
	    NOP
	    DECFSZ	0X63,F
	    GOTO	DECRE2V
	    DECFSZ	0X61,F
	    GOTO	ST2V
	    NOP				; PARA SIMULAR LOS CICLOS DE RETURN Y
	    NOP				; LOS DE CALL
	    NOP
	    NOP
	    ENDM


	    
;   MACRO Y SUBRUTINA DE TRES VARIABLES, CICLOS_MAQ_MAX = 117,703,689
;   SE OCUPA LA DIRECCION 0X64,65,66 DE LA RAM PARA GUARDAR EL VALOR DE VAR1,
;   VAR2,VAR3
;   TAMBIEN SE OCUPAN LOS REGISTROS, 0X67 Y 0X68 COMO AUXILIARES
    
SUBT3V	    MACRO	VAR1,VAR2,VAR3
	    MOVLW	VAR1
	    MOVWF	0X64		; VALOR DE MAYOR PESO EN ANIDACION
	    MOVLW	VAR2
	    MOVWF	0X65
	    MOVLW	VAR3		; VALOR DE MENOR PESO EN ANIDACION
	    MOVWF	0X66
ST3V:	    MOVF	0X65,W		; VAR2
	    MOVWF	0X67
RECARGA3V:  MOVF	0X66,W		; VAR3
	    MOVWF	0X68
DECRE3V:    NOP
	    NOP
	    NOP
	    NOP
	    DECFSZ	0X68,F		; VAR3_AUX
	    GOTO	DECRE3V
	    DECFSZ	0X67,F		; VAR2_AUX
	    GOTO	RECARGA3V
	    DECFSZ	0X64,F		; VAR1
	    GOTO	ST3V
	    NOP				; PARA SIMULAR LOS CICLOS DE RETURN Y
	    NOP				; LOS DE CALL
	    NOP
	    NOP
	    ENDM
	    
	    
	    